//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidate
    {
        public string Id { get; set; }
        public string Pass { get; set; }
        public string HomeAddress { get; set; }
        public bool Gender { get; set; }
        public string WorkExperience { get; set; }
        public string Education { get; set; }
        public System.DateTime Birthday { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public bool Passed { get; set; }
        public Nullable<System.DateTime> DateTaken { get; set; }
        public Nullable<int> Result { get; set; }
        public System.DateTime DateAssigned { get; set; }
    }
}
